name: Java CI with SonarQube

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Set up JDK
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '22'

    # Cache Maven dependencies
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    # Build the project
    - name: Build with Maven
      run: mvn clean verify

    # SonarQube scan
    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONARCLOUD_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
        SONARCLOUD_ORG: 'pchmielecki87'
        SONARCLOUD_PROJECT_KEY: 'java_cicd_sonarqube_githubactions'
      run: |
        mvn sonar:sonar \
        -Dsonar.host.url=https://sonarcloud.io \
        -Dsonar.organization=${SONARCLOUD_ORG} \
        -Dsonar.projectKey=${SONARCLOUD_PROJECT_KEY} \
        -Dsonar.login=${SONARCLOUD_TOKEN} \
        -Dsonar.java.binaries=target/classes
